services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_HOST=redis

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5174:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
